/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JavaAssignment;

import java.io.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Scanner;
import javax.swing.JOptionPane;
/**
 *
 * @author homew
 */
public class AddBookingForm extends javax.swing.JFrame {

    /**
     * Creates new form AddBooking
     */
    public AddBookingForm() {
        initComponents();
        setLocationRelativeTo(null);
        
        //Set date format to yyyy/mm/dd to maintain an correct order throughout entire process
        jtxtstartdate.setDateFormatString("yyyy/MM/dd");
        jtxtenddate.setDateFormatString("yyyy/MM/dd");
        
        //Set date range for users
        Calendar cal = Calendar.getInstance();
        cal.add(Calendar.DATE, 3);
        //Create date variable to get time.
        Date mindate = cal.getTime();
        cal.add(Calendar.YEAR, 1);
        Date maxdate = cal.getTime();
        //Set minimum and maximum date range
        jtxtstartdate.setDate(mindate);
        jtxtstartdate.setSelectableDateRange(mindate, maxdate);
        jtxtenddate.setDate(mindate);
        jtxtenddate.setSelectableDateRange(mindate, maxdate);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtic = new javax.swing.JTextField();
        jtxtnumber = new javax.swing.JTextField();
        jtxtemail = new javax.swing.JTextField();
        jbtnadd = new javax.swing.JButton();
        jbtnclear = new javax.swing.JButton();
        jbtnback = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jtxtcitizenship = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jbtnconfirm = new javax.swing.JButton();
        roomidcombobox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jtxtroomtype1 = new javax.swing.JTextField();
        jtxtprice = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtxtroomid = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtxtstartdate = new com.toedter.calendar.JDateChooser();
        jtxtenddate = new com.toedter.calendar.JDateChooser();
        jspinday = new com.toedter.components.JSpinField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        jLabel1.setText("Add Room Booking");

        jtxtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtnameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Name :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("IC / Passport :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Contact Number :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Email :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Check Out :");

        jtxtic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxticActionPerformed(evt);
            }
        });

        jbtnadd.setText("ADD");
        jbtnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnaddActionPerformed(evt);
            }
        });

        jbtnclear.setText("CLEAR");
        jbtnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnclearActionPerformed(evt);
            }
        });

        jbtnback.setText("BACK");
        jbtnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbackActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("RoomType :");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Jungle View", "Sea View" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jtxtcitizenship.setEditable(false);
        jtxtcitizenship.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtcitizenshipActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Check In :");

        jbtnconfirm.setText("CHECK");
        jbtnconfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnconfirmActionPerformed(evt);
            }
        });

        roomidcombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomidcomboboxActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("RoomID :");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Citizenship :");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Citizen", "Non-Citizen" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jtxtroomtype1.setEditable(false);
        jtxtroomtype1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtroomtype1ActionPerformed(evt);
            }
        });

        jtxtprice.setText("RM");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("No of Days :");

        jLabel12.setText("Price :");

        jtxtroomid.setEditable(false);
        jtxtroomid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtroomidActionPerformed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JavaAssignment/2.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(28, 28, 28)
                                    .addComponent(jbtnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addComponent(jLabel11))
                                            .addGap(186, 186, 186)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jtxtroomtype1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jtxtroomid, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(54, 54, 54)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jtxtname, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jtxtic, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel5))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(roomidcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jtxtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jtxtnumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(jtxtstartdate, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                                                        .addComponent(jtxtenddate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jspinday, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(282, 282, 282)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jtxtcitizenship, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtnconfirm)
                                    .addComponent(jtxtprice, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnclear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtnback, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtcitizenship, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtroomtype1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomidcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jtxtroomid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jtxtstartdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jspinday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jtxtenddate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jbtnconfirm)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnclear)
                    .addComponent(jbtnback, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnadd))
                .addGap(41, 41, 41))
            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtnameActionPerformed
        
    }//GEN-LAST:event_jtxtnameActionPerformed

    private void jbtnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnaddActionPerformed
        //Get input from textbox
        String name = jtxtname.getText();
        String citizenship = jtxtcitizenship.getText();
        String ic = jtxtic.getText();
        String contact = jtxtnumber.getText();
        String email = jtxtemail.getText();
        String roomtype = jtxtroomtype1.getText();
        String roomid = jtxtroomid.getText();
        String price = jtxtprice.getText();
        
        //Set date format
        SimpleDateFormat DateFormat = new SimpleDateFormat("yyyy/MM/dd");
        //Get start and end date entered by the users.
        String startdate = DateFormat.format(jtxtstartdate.getDate());
        String enddate = DateFormat.format(jtxtenddate.getDate());
        
        //Validation Details with input
        int error = Booking.validatebooking(jtxtname.getText(), jtxtic.getText(), jtxtnumber.getText(), jtxtemail.getText(), jLabel3.getText());
        
        //If there is error from validation
        switch (error) {
            case 1:
                JOptionPane.showMessageDialog(this, "Invalid Customer details\nPlease check on customer's name, contact number, and email.", "Message", JOptionPane.ERROR_MESSAGE);
                break;
            case 2:
                JOptionPane.showMessageDialog(this, "Invalid Identification number.", "Message", JOptionPane.ERROR_MESSAGE);
                break;
            case 0:
                //If no error then proceed to this section.
                try
                {
                    //Write input from textbox into the booking details file.
                    File f = new File("bookingdetails.txt");
                    FileWriter fw = new FileWriter(f,true);
                    fw.write("\n"+name+"\n"+citizenship+"\n"+ic+"\n"+contact+"\n"+email+"\n"+roomtype+"\n"+roomid+"\n"+startdate+"\n"+enddate+"\n"+price);
                    fw.close();
            
                    //Once all data are insert then set all data into null (empty values).
                    jtxtname.setText(null);
                    jtxtic.setText(null);
                    jtxtnumber.setText(null);
                    jtxtemail.setText(null);
                    jtxtcitizenship.setText(null);
                    jtxtroomtype1.setText(null);
                    jtxtroomid.setText(null);
                    jtxtprice.setText(null);
                    JOptionPane.showMessageDialog(null,"Successfully Added.");
            
                    this.setVisible(false);
                    SearchBookingListForm Info =new SearchBookingListForm();
                    Info.setVisible(true);
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,"System Error");
                }
        }
        
        
        
        
    }//GEN-LAST:event_jbtnaddActionPerformed

    private void jbtnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnclearActionPerformed
        jtxtname.setText(null);
        jtxtic.setText(null);
        jtxtnumber.setText(null);
        jtxtemail.setText(null);
        jtxtcitizenship.setText(null);
        jtxtroomtype1.setText(null);
        jtxtroomid.setText(null);
        jtxtprice.setText(null);
    }//GEN-LAST:event_jbtnclearActionPerformed

    private void jbtnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbackActionPerformed
        this.setVisible(false);
        RoomBookingMain Info =new RoomBookingMain();
        Info.setVisible(true);
    }//GEN-LAST:event_jbtnbackActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if(jComboBox1.getSelectedItem().equals("Jungle View"))
        {
            jtxtroomtype1.setText("Jungle View");
        }
        if(jComboBox1.getSelectedItem().equals("Sea View"))
        {
            jtxtroomtype1.setText("Sea View");
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jbtnconfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnconfirmActionPerformed
        //Remove all items from the Room ID combo box
        roomidcombobox.removeAllItems();


        //Adding item in the RoomID combo box
        //Check if textbox  input = Jungle View
        if(jtxtroomtype1.getText().equals("Jungle View"))
        {
        try 
        {
            //Read all data from Jungle Room file like all room ID.
            File jungleroomfile = new File("jungleroom.txt");
            Scanner myReader = new Scanner(jungleroomfile);
            while (myReader.hasNextLine()) {
                String data = myReader.nextLine();
                roomidcombobox.addItem(data);
            }
        } 
        catch (FileNotFoundException e) 
        {
        System.out.println("File not found.");
        }
        
        try {
            //Set date format
            SimpleDateFormat DateFormat = new SimpleDateFormat("yyyy/MM/dd");

            //Get start date input and convert into string.
            String startdate = DateFormat.format(jtxtstartdate.getDate());

            //Get end date input and convert into string.
            String enddate = DateFormat.format(jtxtenddate.getDate());


            //Arraylist will store and list out all the booked room id received from the function below.
            ArrayList<String> bookedroomid = Booking.bookedroomid(startdate, enddate);

            //Delete the booked room id contained in the arraylist from the RoomID combo box
            int index = 0;
            while (index < bookedroomid.size()) {
                roomidcombobox.removeItem(bookedroomid.get(index));
                index++;
            }
                
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Please insert a date.", "Message", JOptionPane.ERROR_MESSAGE);
        }
        }
        //Adding item in the RoomID combo box
        //Check textbox input = Sea View
        if(jtxtroomtype1.getText().equals("Sea View"))
        {
        try 
        {
            //Read all data from Jungle Room file like all room ID.
            File searoomfile = new File("searoom.txt");
            Scanner myReader = new Scanner(searoomfile);
            while (myReader.hasNextLine()) {
                String data = myReader.nextLine();
                roomidcombobox.addItem(data);
            }
        } 
        catch (FileNotFoundException e) 
        {
        System.out.println("File not found.");
        }
        
        try {
            //Set Date format
            SimpleDateFormat DateFormat = new SimpleDateFormat("yyyy/MM/dd");

            //Receive start date input and convert into string.
            String startdate = DateFormat.format(jtxtstartdate.getDate());

            //Receive end date input and convert into string.
            String enddate = DateFormat.format(jtxtenddate.getDate());


            //Arraylist will store and list out all the booked room id received from the function below.
            ArrayList<String> bookedroomid = Booking.bookedroomid(startdate, enddate);

            //Delete the booked room id contained in the arraylist from the RoomID combo box
            int index = 0;
            while (index < bookedroomid.size()) {
                roomidcombobox.removeItem(bookedroomid.get(index));
                index++;
            }
                
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Please insert a date.", "Message", JOptionPane.ERROR_MESSAGE);
        }
        }
        
        //Calculate the price for different type of customer like citizen or non-citizen.
        if (jtxtcitizenship.getText().equals("Citizen")) {
            int price = ((Integer) jspinday.getValue() * 350) * 110 / 100;
            jtxtprice.setText("RM " + String.valueOf(price));
        } else {
            int price = (((Integer) jspinday.getValue() * 350) * 110 / 100) + ((Integer) jspinday.getValue() * 10);
            jtxtprice.setText("RM " + String.valueOf(price));
        }
   
    }//GEN-LAST:event_jbtnconfirmActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        if(jComboBox2.getSelectedItem().equals("Citizen"))
        {
            jtxtcitizenship.setText("Citizen");
        }
        if(jComboBox2.getSelectedItem().equals("Non-Citizen"))
        {
            jtxtcitizenship.setText("Non-Citizen");
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jtxticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxticActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxticActionPerformed

    private void jtxtcitizenshipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtcitizenshipActionPerformed
        
    }//GEN-LAST:event_jtxtcitizenshipActionPerformed

    private void jtxtroomtype1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtroomtype1ActionPerformed

    }//GEN-LAST:event_jtxtroomtype1ActionPerformed

    private void roomidcomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomidcomboboxActionPerformed
        Object name;
        name = roomidcombobox.getSelectedItem();
        jtxtroomid.setText((String) name);
    }//GEN-LAST:event_roomidcomboboxActionPerformed

    private void jtxtroomidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtroomidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtroomidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBookingForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbtnadd;
    private javax.swing.JButton jbtnback;
    private javax.swing.JButton jbtnclear;
    private javax.swing.JButton jbtnconfirm;
    private com.toedter.components.JSpinField jspinday;
    private javax.swing.JTextField jtxtcitizenship;
    private javax.swing.JTextField jtxtemail;
    private com.toedter.calendar.JDateChooser jtxtenddate;
    private javax.swing.JTextField jtxtic;
    private javax.swing.JTextField jtxtname;
    private javax.swing.JTextField jtxtnumber;
    private javax.swing.JTextField jtxtprice;
    private javax.swing.JTextField jtxtroomid;
    private javax.swing.JTextField jtxtroomtype1;
    private com.toedter.calendar.JDateChooser jtxtstartdate;
    private javax.swing.JComboBox<String> roomidcombobox;
    // End of variables declaration//GEN-END:variables
}
