/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JavaAssignment;

import java.io.File;
import java.io.FileNotFoundException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author homew
 */
public class ModifyBookingForm extends javax.swing.JFrame {

    /**
     * Creates new form ModifyBooking
     * @param selectedid
     */
    public ModifyBookingForm(String selectedid) {
        initComponents();
        setLocationRelativeTo(null);
        
        //Set date format to yyyy/mm/dd to maintain an correct order throughout entire process
        jtxtstartdate.setDateFormatString("yyyy/MM/dd");
        
        //Set date range for user
        Calendar cal = Calendar.getInstance();
        cal.add(Calendar.YEAR, 1);
        //Set date variable to get time input
        Date mindate = cal.getTime();
        Date maxdate = cal.getTime();
        jtxtstartdate.setDate(mindate);
        jtxtstartdate.setSelectableDateRange(mindate, maxdate);
        
        //Load and store all the booking record data into an arraylist
        ArrayList<String> bookingdata = LoadData.bookingdata();
        
        //Create an arraylist to append the new selected booking data
        ArrayList<String> data = new ArrayList<String>();

        //Load out data of the booking which has the same room id with the String selectedid
        int index = 0, count = 0;
        while (index < bookingdata.size()) {
            if (bookingdata.get(index).equals(selectedid)) {
                count = index;
                break;
            }
            index++;
        }
        //One Room booking data contains 10 different data so repeat steps 10 times.
        for (int i = 0; i != 10; i++) {
            data.add(bookingdata.get(count));
            count++;
        }
        
        //Create Date format
        SimpleDateFormat DateFormat = new SimpleDateFormat("yyyy/MM/dd");
        
        //Set startdate and enddate into null and extract startdate and enddate data.
        Date startdate = null, enddate = null;
        try {
            //Start date is contained in the index 7 of the list and End date contained in the index 8 of the list.
            startdate = DateFormat.parse(data.get(7));
            enddate = DateFormat.parse(data.get(8));
        } catch (Exception e1) {
            JOptionPane.showMessageDialog(null,"System Error");
        }
        
        //Get the number of days booked by minusing enddate and startdate
        long difference = enddate.getTime() - startdate.getTime();
        int numofday = (int)difference/86400000 + 1;       

        //Setting all the details in the form according to the index count.
        jtxtstartdate.setDate(startdate);
        jtxtenddate.setDate(enddate);
        jtxtcitizenship.setText(data.get(1));
        jspinday.setValue(numofday);
        roomidcombobox.addItem(data.get(6));
        jtxtname.setText(data.get(0));
        jtxtic.setText(data.get(2));
        jtxtnumber.setText(data.get(3));
        jtxtemail.setText(data.get(4));
        jtxtroomtype1.setText(data.get(5));
        jtxtprice.setText(data.get(9));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jspinday = new com.toedter.components.JSpinField();
        jtxtroomid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtic = new javax.swing.JTextField();
        jtxtnumber = new javax.swing.JTextField();
        jtxtemail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jtxtcitizenship = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        roomidcombobox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jtxtstartdate = new com.toedter.calendar.JDateChooser();
        jtxtenddate = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jtxtroomtype1 = new javax.swing.JTextField();
        jtxtname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtxtprice = new javax.swing.JTextField();
        jbtnmodify = new javax.swing.JButton();
        jbtnback = new javax.swing.JButton();
        jbtncheck = new javax.swing.JButton();
        jbtndelete = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        jLabel1.setText("Modify Booking");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Contact Number :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Email :");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("No of Days :");

        jtxtroomid.setEditable(false);
        jtxtroomid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtroomidActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Check Out :");

        jtxtic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxticActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("RoomType :");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Jungle View", "Sea View" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jtxtcitizenship.setEditable(false);
        jtxtcitizenship.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtcitizenshipActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Check In :");

        roomidcombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomidcomboboxActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("RoomID :");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Citizenship :");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Citizen", "Non-Citizen" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jtxtroomtype1.setEditable(false);
        jtxtroomtype1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtroomtype1ActionPerformed(evt);
            }
        });

        jtxtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtnameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Name :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("IC / Passport :");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Price ( Tax Included ) :");

        jtxtprice.setText("RM");

        jbtnmodify.setText("MODIFY");
        jbtnmodify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmodifyActionPerformed(evt);
            }
        });

        jbtnback.setText("BACK");
        jbtnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbackActionPerformed(evt);
            }
        });

        jbtncheck.setText("CHECK");
        jbtncheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncheckActionPerformed(evt);
            }
        });

        jbtndelete.setText("DELETE");
        jbtndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndeleteActionPerformed(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JavaAssignment/4.png"))); // NOI18N
        jLabel14.setText("jLabel14");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addContainerGap(262, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jLabel12)
                                .addGap(32, 32, 32)
                                .addComponent(jtxtprice, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jbtnmodify)
                                        .addGap(57, 57, 57)
                                        .addComponent(jbtndelete)
                                        .addGap(74, 74, 74)
                                        .addComponent(jbtnback))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jtxtic)
                                                        .addComponent(jtxtname, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(241, 241, 241)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jtxtroomtype1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jtxtroomid, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel5)
                                                        .addComponent(jLabel11))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jspinday, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(roomidcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jtxtstartdate, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                                                        .addComponent(jtxtemail)
                                                        .addComponent(jtxtnumber)
                                                        .addComponent(jtxtenddate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(282, 282, 282)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jtxtcitizenship))))))
                        .addContainerGap(37, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jbtncheck)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtcitizenship, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtroomtype1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomidcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jtxtroomid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jtxtstartdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jspinday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtenddate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtncheck)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jtxtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtndelete)
                    .addComponent(jbtnmodify)
                    .addComponent(jbtnback))
                .addGap(44, 44, 44))
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtroomidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtroomidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtroomidActionPerformed

    private void jtxticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxticActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxticActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if(jComboBox1.getSelectedItem().equals("Jungle View"))
        {
            jtxtroomtype1.setText("Jungle View");
        }
        if(jComboBox1.getSelectedItem().equals("Sea View"))
        {
            jtxtroomtype1.setText("Sea View");
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jtxtcitizenshipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtcitizenshipActionPerformed

    }//GEN-LAST:event_jtxtcitizenshipActionPerformed

    private void roomidcomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomidcomboboxActionPerformed
        Object name;
        name = roomidcombobox.getSelectedItem();
        jtxtroomid.setText((String) name);
    }//GEN-LAST:event_roomidcomboboxActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        if(jComboBox2.getSelectedItem().equals("Citizen"))
        {
            jtxtcitizenship.setText("Citizen");
        }
        if(jComboBox2.getSelectedItem().equals("Non-Citizen"))
        {
            jtxtcitizenship.setText("Non-Citizen");
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jtxtroomtype1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtroomtype1ActionPerformed

    }//GEN-LAST:event_jtxtroomtype1ActionPerformed

    private void jtxtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtnameActionPerformed

    }//GEN-LAST:event_jtxtnameActionPerformed

    private void jbtnmodifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmodifyActionPerformed
        //Set date format to yyyy/mm/dd to maintain an correct order throughout entire process
        SimpleDateFormat DateFormat = new SimpleDateFormat("yyyy/MM/dd");
        try {
            //Get date and convert to String
            String startdate = DateFormat.format(jtxtstartdate.getDate());
        } catch (NullPointerException e) {
            //Date Validation
            JOptionPane.showMessageDialog(this, "Please Insert a Date.", "Message", JOptionPane.ERROR_MESSAGE);
        }

        //Validation for text input
        int error = Booking.validatebooking(jtxtname.getText(), jtxtic.getText(), jtxtnumber.getText(), jtxtemail.getText(), jLabel3.getText());

        //If there is error from the validation then output the following.
        switch (error) {
            case 1:
            JOptionPane.showMessageDialog(this, "Invalid Customer details\nPlease check on customer's name, contact number, and email.", "Message", JOptionPane.ERROR_MESSAGE);
            break;
            case 2:
            JOptionPane.showMessageDialog(this, "Invalid Identification number.", "Message", JOptionPane.ERROR_MESSAGE);
            break;
            //If there is no error then case 0 and proceed with modification function.
            case 0:
            //Get start date from input
            String startdate = DateFormat.format(jtxtstartdate.getDate());

            //Get end date from input
            String enddate = DateFormat.format(jtxtenddate.getDate());
            
            //Modify booking from all input
            Booking.modifybooking(jtxtname.getText(), jtxtcitizenship.getText(), jtxtic.getText(), jtxtnumber.getText(), jtxtemail.getText(), jtxtroomtype1.getText(), roomidcombobox.getSelectedItem().toString(), startdate, enddate, jtxtprice.getText());
            
            //Once modification is successful then display Successfully Modified and prompt the Search Booking List Form to the user.
            JOptionPane.showMessageDialog(this, "Successfully Modified.");
            SearchBookingListForm brf = new SearchBookingListForm();
            brf.setLocationRelativeTo(null);
            brf.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jbtnmodifyActionPerformed

    private void jbtnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbackActionPerformed
        SearchBookingListForm brf = new SearchBookingListForm();
        brf.setLocationRelativeTo(null);
        brf.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbtnbackActionPerformed

    private void jbtncheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncheckActionPerformed
        //Remove all items from the Room ID combo box
        roomidcombobox.removeAllItems();


        //Adding item in the RoomID combo box
        //Check if textbox  input = Jungle View
        if(jtxtroomtype1.getText().equals("Jungle View"))
        {
        try 
        {
            //Read all data from Jungle Room file like all room ID.
            File jungleroomfile = new File("jungleroom.txt");
            Scanner myReader = new Scanner(jungleroomfile);
            while (myReader.hasNextLine()) {
                String data = myReader.nextLine();
                roomidcombobox.addItem(data);
            }
        } 
        catch (FileNotFoundException e) 
        {
        System.out.println("File not found.");
        }
        
        try {
            //Set date format
            SimpleDateFormat DateFormat = new SimpleDateFormat("yyyy/MM/dd");

            //Get start date input and convert into string.
            String startdate = DateFormat.format(jtxtstartdate.getDate());

            //Get end date input and convert into string.
            String enddate = DateFormat.format(jtxtenddate.getDate());


            //Arraylist will store and list out all the booked room id received from the function below.
            ArrayList<String> bookedroomid = Booking.bookedroomid(startdate, enddate);

            //Delete the booked room id contained in the arraylist from the RoomID combo box
            int index = 0;
            while (index < bookedroomid.size()) {
                roomidcombobox.removeItem(bookedroomid.get(index));
                index++;
            }
                
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Please insert a date.", "Message", JOptionPane.ERROR_MESSAGE);
        }
        }
        
        //Adding item in the RoomID combo box
        //Check textbox input = Sea View
        if(jtxtroomtype1.getText().equals("Sea View"))
        {
        try 
        {
            //Read all data from Jungle Room file like all room ID.
            File searoomfile = new File("searoom.txt");
            Scanner myReader = new Scanner(searoomfile);
            while (myReader.hasNextLine()) {
                String data = myReader.nextLine();
                roomidcombobox.addItem(data);
            }
        } 
        catch (FileNotFoundException e) 
        {
        System.out.println("File not found.");
        }
        
        try {
            //Set Date format
            SimpleDateFormat DateFormat = new SimpleDateFormat("yyyy/MM/dd");

            //Receive start date input and convert into string.
            String startdate = DateFormat.format(jtxtstartdate.getDate());

            //Receive end date input and convert into string.
            String enddate = DateFormat.format(jtxtenddate.getDate());


            //Arraylist will store and list out all the booked room id received from the function below.
            ArrayList<String> bookedroomid = Booking.bookedroomid(startdate, enddate);

            //Delete the booked room id contained in the arraylist from the RoomID combo box
            int index = 0;
            while (index < bookedroomid.size()) {
                roomidcombobox.removeItem(bookedroomid.get(index));
                index++;
            }
                
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Please insert a date.", "Message", JOptionPane.ERROR_MESSAGE);
        }
        }
        
        //Calculate the price for different type of customer like citizen or non-citizen.
        if (jtxtcitizenship.getText().equals("Citizen")) {
            int price = ((Integer) jspinday.getValue() * 350) * 110 / 100;
            jtxtprice.setText("RM " + String.valueOf(price));
        } else {
            int price = (((Integer) jspinday.getValue() * 350) * 110 / 100) + ((Integer) jspinday.getValue() * 10);
            jtxtprice.setText("RM " + String.valueOf(price));
        }
        
    }//GEN-LAST:event_jbtncheckActionPerformed

    private void jbtndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndeleteActionPerformed
        //Once buttun is selected, delete booking function will be proceed with the customer name from the textbox input.
        Booking.deletebooking(jtxtname.getText());
        //Once deletion successful then display Successfully deleted and prompt user to the Search Booking List Form.
        JOptionPane.showMessageDialog(this, "Successfully Deleted.");
        SearchBookingListForm brf = new SearchBookingListForm();
        brf.setLocationRelativeTo(null);
        brf.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbtndeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyBookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyBookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyBookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyBookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifyBookingForm("1").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbtnback;
    private javax.swing.JButton jbtncheck;
    private javax.swing.JButton jbtndelete;
    private javax.swing.JButton jbtnmodify;
    private com.toedter.components.JSpinField jspinday;
    private javax.swing.JTextField jtxtcitizenship;
    private javax.swing.JTextField jtxtemail;
    private com.toedter.calendar.JDateChooser jtxtenddate;
    private javax.swing.JTextField jtxtic;
    private javax.swing.JTextField jtxtname;
    private javax.swing.JTextField jtxtnumber;
    private javax.swing.JTextField jtxtprice;
    private javax.swing.JTextField jtxtroomid;
    private javax.swing.JTextField jtxtroomtype1;
    private com.toedter.calendar.JDateChooser jtxtstartdate;
    private javax.swing.JComboBox<String> roomidcombobox;
    // End of variables declaration//GEN-END:variables
}
